### PR TITLE
Adding KeypointResnet

### PR DESCRIPTION
**Pull request by RaresAmbrus**
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/kp2d/15)

### CODE REVIEW

**Review by RaresAmbrus — COMMENTED** [review]
+@vitorguizilini-tri 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/kp2d/15#-:-MRTk7n2ABVhsqPtvwKE:bek7r6y)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @VitorGuizilini-TRI)

**Review by VitorGuizilini-TRI — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/kp2d/15)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[kp2d/configs/base_config.py, line 59 at r1](https://reviewable.io/reviews/tri-ml/kp2d/15#-MRVj-Dj2ZzlTE-aFFPa:-MRVj-Dj2ZzlTE-aFFPb:brgh1im) ([raw file](https://github.com/tri-ml/kp2d/blob/e43e214d8ce7d391a5fe16bb3f34c41c77f559b7/kp2d/configs/base_config.py#L59)):*
> ```Python
> cfg.model.params.do_cross = True                            # Use cross-border keypoints
> cfg.model.params.descriptor_loss = True                     # Use hardest negative mining descriptor loss
> cfg.model.params.keypoint_net_type = 'KeypointNet'
> ```

BTW Some descriptive comment here?

**Review by RaresAmbrus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/kp2d/15)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @VitorGuizilini-TRI)

___
*[kp2d/configs/base_config.py, line 59 at r1](https://reviewable.io/reviews/tri-ml/kp2d/15#-MRVj-Dj2ZzlTE-aFFPa:-MRVtAzDAwFDk-g-NHIE:b-896fix) ([raw file](https://github.com/tri-ml/kp2d/blob/e43e214d8ce7d391a5fe16bb3f34c41c77f559b7/kp2d/configs/base_config.py#L59)):*
<details><summary><i>Previously, VitorGuizilini-TRI wrote…</i></summary><blockquote>

BTW Some descriptive comment here?
</blockquote></details>

Done.

**Review by RaresAmbrus — COMMENTED** [review]
@vitorguizilini-tri I think you may have to approve again, I updated the PR with a small comment.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/kp2d/15#-:-MRVtFkcBNDdZh6xwnpj:b2ayheg)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @VitorGuizilini-TRI)

**Pull request merged**
